// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf21qeWlL-1xcsKt4ptmBoCFsYsoxP3xA',
    appId: '1:281322148820:android:5db75e60b533d55c647c41',
    messagingSenderId: '281322148820',
    projectId: 'getwell-ab06b',
    databaseURL: 'https://getwell-ab06b-default-rtdb.firebaseio.com',
    storageBucket: 'getwell-ab06b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJTbtModkXxGcLVEwOQ4obOKittZiB1QQ',
    appId: '1:281322148820:ios:584bebc3e8710b0b647c41',
    messagingSenderId: '281322148820',
    projectId: 'getwell-ab06b',
    databaseURL: 'https://getwell-ab06b-default-rtdb.firebaseio.com',
    storageBucket: 'getwell-ab06b.firebasestorage.app',
    iosClientId: '281322148820-3ch9a4fsnot091eft8omeu6uurgogihh.apps.googleusercontent.com',
    iosBundleId: 'com.rahul.jobhunt.blocCleanArchitecture',
  );
}
